In [1]:
# Datascience lesson - Quant and Qual_Placement data file_Practicals

In [2]:
import pandas as pd

In [3]:
dataset = pd.read_csv("Placement.csv")
dataset

,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [4]:
dataset.columns

Index(['gender', 'ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s', 'degree_p',
       'degree_t', 'workex', 'etest_p', 'specialisation', 'mba_p', 'status',
       'salary'],
      dtype='str')

In [5]:
#qual = ['gender','ssc_b','hsc_b','hsc_s','degree_t,'workex','specialisation','status']
#quant = ['ssc_p','hsc_p','degree_p','etest_p',mba_p','salary']

In [6]:
for columnname in dataset.columns:
    print (columnname)

gender
ssc_p
ssc_b
hsc_p
hsc_b
hsc_s
degree_p
degree_t
workex
etest_p
specialisation
mba_p
status
salary

In [7]:
if (dataset[columnname].dtypes=="str"):
    print ("qual")
else:
    print ("quant")

quant

In [8]:
for columnname in dataset.columns:
    print (columnname)
    if (dataset[columnname].dtypes=="str"):
        print ("qual")
    else:
        print ("quant")

gender
qual
ssc_p
quant
ssc_b
qual
hsc_p
quant
hsc_b
qual
hsc_s
qual
degree_p
quant
degree_t
qual
workex
qual
etest_p
quant
specialisation
qual
mba_p
quant
status
qual
salary
quant

In [9]:
quan=[]
qual=[]
for columnname in dataset.columns:
    print (columnname)
    if (dataset[columnname].dtypes=="str"):
        print ("qual")
        qual.append (columnname)
    else:
        print ("quant")
        quan.append (columnname)

gender
qual
ssc_p
quant
ssc_b
qual
hsc_p
quant
hsc_b
qual
hsc_s
qual
degree_p
quant
degree_t
qual
workex
qual
etest_p
quant
specialisation
qual
mba_p
quant
status
qual
salary
quant

In [10]:
quan

['ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

In [11]:
qual

['gender',
 'ssc_b',
 'hsc_b',
 'hsc_s',
 'degree_t',
 'workex',
 'specialisation',
 'status']

In [12]:
def quanqual(dataset):
    quan=[]
    qual=[]
    for columnname in dataset.columns:
        print (columnname)
        if (dataset[columnname].dtypes=="str"):
            print ("qual")
            qual.append (columnname)
        else:
            print ("quant")
            quan.append (columnname)
    return quan,qual

In [13]:
quanqual(dataset)

gender
qual
ssc_p
quant
ssc_b
qual
hsc_p
quant
hsc_b
qual
hsc_s
qual
degree_p
quant
degree_t
qual
workex
qual
etest_p
quant
specialisation
qual
mba_p
quant
status
qual
salary
quant

(['ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary'],
 ['gender',
  'ssc_b',
  'hsc_b',
  'hsc_s',
  'degree_t',
  'workex',
  'specialisation',
  'status'])

In [14]:
dataset

,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

# Central Tendency

In [15]:
dataset["ssc_p"].mean()

np.float64(67.30339534883721)

In [16]:
dataset["ssc_p"].median()

np.float64(67.0)

In [17]:
dataset["ssc_p"].mode()[0]

np.float64(62.0)

In [18]:
tablecreate=pd.DataFrame(index=["Mean","Median","Mode"],columns=quan)

In [19]:
tablecreate

       ssc_p hsc_p degree_p etest_p mba_p salary
Mean     NaN   NaN      NaN     NaN   NaN    NaN
Median   NaN   NaN      NaN     NaN   NaN    NaN
Mode     NaN   NaN      NaN     NaN   NaN    NaN

In [20]:
tablecreate.loc["Mean","hsc_p"]=0

In [21]:
tablecreate

       ssc_p hsc_p degree_p etest_p mba_p salary
Mean     NaN     0      NaN     NaN   NaN    NaN
Median   NaN   NaN      NaN     NaN   NaN    NaN
Mode     NaN   NaN      NaN     NaN   NaN    NaN

In [22]:
tablecreate=pd.DataFrame(index=["Mean","Median","Mode"],columns=quan)
for columnName in quan:
    tablecreate.loc["Mean",columnName]=dataset[columnName].mean()
    tablecreate.loc["Median",columnName]=dataset[columnName].median()
    tablecreate.loc["Mode",columnName]=dataset[columnName].mode()[0]
print(tablecreate)

            ssc_p      hsc_p   degree_p    etest_p      mba_p         salary
Mean    67.303395  66.333163  66.370186  72.100558  62.278186  288655.405405
Median       67.0       65.0       66.0       71.0       62.0       265000.0
Mode         62.0       63.0       65.0       60.0       56.7       300000.0

In [23]:
import numpy as np

In [24]:
np.percentile(dataset["ssc_p"],60)

np.float64(70.0)

In [25]:
tablecreate=pd.DataFrame(index=["Mean","Median","Mode","Q1:25","Q2:50","Q3:75","Q4:100"],columns=quan)
for columnName in quan:
    tablecreate.loc["Mean",columnName]=dataset[columnName].mean()
    tablecreate.loc["Median",columnName]=dataset[columnName].median()
    tablecreate.loc["Mode",columnName]=dataset[columnName].mode()[0]
print(tablecreate)

            ssc_p      hsc_p   degree_p    etest_p      mba_p         salary
Mean    67.303395  66.333163  66.370186  72.100558  62.278186  288655.405405
Median       67.0       65.0       66.0       71.0       62.0       265000.0
Mode         62.0       63.0       65.0       60.0       56.7       300000.0
Q1:25         NaN        NaN        NaN        NaN        NaN            NaN
Q2:50         NaN        NaN        NaN        NaN        NaN            NaN
Q3:75         NaN        NaN        NaN        NaN        NaN            NaN
Q4:100        NaN        NaN        NaN        NaN        NaN            NaN

In [26]:
tablecreate=pd.DataFrame(index=["Mean","Median","Mode","Q1:25","Q2:50","Q3:75","Q4:100"],columns=quan)
for columnName in quan:
    tablecreate.loc[columnName]["Mean"]=dataset[columnname].mean()
    tablecreate.loc[columnName]["Median"]=dataset[columnname].median()
    tablecreate.loc[columnName]["Mode"]=dataset[columnname].mode()[0]
    tablecreate.loc[columnName]["Q1:25"]=np.percentile(dataset[columnname],60)
print(tablecreate)

KeyError: 'ssc_p'